---
title: "Data Tidying"
author: "AMBenson"
date: "October 16, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r,warning=F, message=F}

setwd("C:/Users/AMBenson/Documents/R Training")
library(dplyr)
library(tidyr)

```
 get catch data 
```{r read catch data}
catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_df)

```

`select`the columns we need for analysis
`gather` to move from wide to long
```{r use gather spread}
catch_clean<-catch_df %>% 
    #select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum) %>% 
    select(-All,-notesRegCode) %>% 
    gather(key="Species", value="catch",-Region,-Year) %>% 
    ##opposite of gather is spread (to put it back the way it was)
    #spread(key="Species", value="catch")##key is what you turn into column names
    rename(catch_thousands=catch)
    head(catch_clean)
    ##we want to gather over the species columns ... is selection of columns
```

```{r}
test<-as.numeric(catch_clean$catch_thousands)
##find out which row got turned into an NA
i<-which(is.na(test)==T)
catch_clean[i,]
##find out it is row 401
##it is a Captial I
###the data were scanned and accidentally 
```
`mutate` to create a new catch column
fix typeo in orignal dataset original data set had an I instead of 1
coerce tto catch to numeric
```{r}
catch_clean_mutated<-catch_clean %>%
  mutate(catch_thousands=ifelse(catch_thousands=="I",1,catch_thousands)) %>% 
  mutate(catch_thousands=as.numeric(catch_thousands)) %>% 
  mutate(catch=catch_thousands*1000) %>% 
  select(-catch_thousands)
tail(catch_clean_mutated)
```

Most useful functions
split using `group_by`
apply and combine using `summarize`

```{r}
catch_summarized<-catch_clean_mutated%>%
  group_by(Year,Region) %>% 
  summarize(mean_catch=mean(catch),
  n_obs=n())
tail(catch_summarized)
```
```{r}
catch_chinook<-catch_clean_mutated %>% 
  filter(Species=="Chinook")
  arrange(-catch)
tail(catch_chinook)
  
```

